%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
clear global
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'Paper_v3';
%
% Some global variables initialization
%
global_initialization;
diary off;
logname_ = 'Paper_v3.log';
if exist(logname_, 'file')
    delete(logname_)
end
diary(logname_)
M_.exo_names = 'ee_a';
M_.exo_names_tex = 'ee\_a';
M_.exo_names = char(M_.exo_names, 'ee_I');
M_.exo_names_tex = char(M_.exo_names_tex, 'ee\_I');
M_.exo_names = char(M_.exo_names, 'ee_b');
M_.exo_names_tex = char(M_.exo_names_tex, 'ee\_b');
M_.exo_names = char(M_.exo_names, 'ee_L');
M_.exo_names_tex = char(M_.exo_names_tex, 'ee\_L');
M_.exo_names = char(M_.exo_names, 'ee_G');
M_.exo_names_tex = char(M_.exo_names_tex, 'ee\_G');
M_.exo_names = char(M_.exo_names, 'ee_pi');
M_.exo_names_tex = char(M_.exo_names_tex, 'ee\_pi');
M_.exo_names = char(M_.exo_names, 'n_p');
M_.exo_names_tex = char(M_.exo_names_tex, 'n\_p');
M_.exo_names = char(M_.exo_names, 'n_Q');
M_.exo_names_tex = char(M_.exo_names_tex, 'n\_Q');
M_.exo_names = char(M_.exo_names, 'n_R');
M_.exo_names_tex = char(M_.exo_names_tex, 'n\_R');
M_.exo_names = char(M_.exo_names, 'n_w');
M_.exo_names_tex = char(M_.exo_names_tex, 'n\_w');
M_.endo_names = 'pi';
M_.endo_names_tex = 'pi';
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names = char(M_.endo_names, 'e_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_a');
M_.endo_names = char(M_.endo_names, 'e_I');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_I');
M_.endo_names = char(M_.endo_names, 'e_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_b');
M_.endo_names = char(M_.endo_names, 'e_L');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_L');
M_.endo_names = char(M_.endo_names, 'e_G');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_G');
M_.endo_names = char(M_.endo_names, 'e_pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_pi');
M_.param_names = 'h';
M_.param_names_tex = 'h';
M_.param_names = char(M_.param_names, 'sigma_c');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_c');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names = char(M_.param_names, 'adj');
M_.param_names_tex = char(M_.param_names_tex, 'adj');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names = char(M_.param_names, 'gamma_p');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_p');
M_.param_names = char(M_.param_names, 'xi_p');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_p');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names = char(M_.param_names, 'gamma_w');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_w');
M_.param_names = char(M_.param_names, 'xi_w');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_w');
M_.param_names = char(M_.param_names, 'sigma_L');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_L');
M_.param_names = char(M_.param_names, 'lambda_w');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_w');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names = char(M_.param_names, 'k');
M_.param_names_tex = char(M_.param_names_tex, 'k');
M_.param_names = char(M_.param_names, 'g');
M_.param_names_tex = char(M_.param_names_tex, 'g');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names = char(M_.param_names, 'r_pi');
M_.param_names_tex = char(M_.param_names_tex, 'r\_pi');
M_.param_names = char(M_.param_names, 'r_Y');
M_.param_names_tex = char(M_.param_names_tex, 'r\_Y');
M_.param_names = char(M_.param_names, 'r_dpi');
M_.param_names_tex = char(M_.param_names_tex, 'r\_dpi');
M_.param_names = char(M_.param_names, 'r_dY');
M_.param_names_tex = char(M_.param_names_tex, 'r\_dY');
M_.param_names = char(M_.param_names, 'r_a');
M_.param_names_tex = char(M_.param_names_tex, 'r\_a');
M_.param_names = char(M_.param_names, 'r_L');
M_.param_names_tex = char(M_.param_names_tex, 'r\_L');
M_.param_names = char(M_.param_names, 'r_k');
M_.param_names_tex = char(M_.param_names_tex, 'r\_k');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names = char(M_.param_names, 'rho_I');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_I');
M_.param_names = char(M_.param_names, 'rho_b');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_b');
M_.param_names = char(M_.param_names, 'rho_L');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_L');
M_.param_names = char(M_.param_names, 'rho_G');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_G');
M_.param_names = char(M_.param_names, 'rho_pi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_pi');
M_.param_names = char(M_.param_names, 'sd_Q');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_Q');
M_.param_names = char(M_.param_names, 'sd_p');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_p');
M_.param_names = char(M_.param_names, 'sd_w');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_w');
M_.param_names = char(M_.param_names, 'sd_R');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_R');
M_.exo_det_nbr = 0;
M_.exo_nbr = 10;
M_.endo_nbr = 16;
M_.param_nbr = 34;
M_.orig_endo_nbr = 16;
M_.aux_vars = [];
options_.varobs = [];
options_.varobs = 'Y';
options_.varobs = char(options_.varobs, 'C');
options_.varobs = char(options_.varobs, 'I');
options_.varobs = char(options_.varobs, 'pi');
options_.varobs = char(options_.varobs, 'w');
options_.varobs = char(options_.varobs, 'L');
options_.varobs_id = [ 10 6 5 1 2 9  ];
M_.Sigma_e = zeros(10, 10);
M_.H = 0;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('Paper_v3_static');
erase_compiled_function('Paper_v3_dynamic');
M_.lead_lag_incidence = [
 1 14 30;
 2 15 31;
 3 16 0;
 0 17 32;
 4 18 33;
 5 19 34;
 6 20 0;
 0 21 35;
 0 22 0;
 7 23 0;
 8 24 0;
 9 25 0;
 10 26 0;
 11 27 0;
 12 28 0;
 13 29 0;]';
M_.nstatic = 1;
M_.nfwrd   = 2;
M_.npred   = 9;
M_.nboth   = 4;
M_.equations_tags = {
};
M_.state_var = [1 2 3 5 6 7 10 11 12 13 14 15 16 ];
M_.exo_names_orig_ord = [1:10];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(16, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(10, 1);
M_.params = NaN(34, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 79;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 1 ) = 0.541;
h = M_.params( 1 );
M_.params( 2 ) = 1.607;
sigma_c = M_.params( 2 );
M_.params( 3 ) = 0.99;
beta = M_.params( 3 );
M_.params( 4 ) = 5.911;
adj = M_.params( 4 );
M_.params( 5 ) = 0.025;
tau = M_.params( 5 );
M_.params( 6 ) = 0.408;
gamma_p = M_.params( 6 );
M_.params( 7 ) = 0.91;
xi_p = M_.params( 7 );
M_.params( 8 ) = 0.3;
alpha = M_.params( 8 );
M_.params( 9 ) = 0.656;
gamma_w = M_.params( 9 );
M_.params( 10 ) = 0.763;
xi_w = M_.params( 10 );
M_.params( 11 ) = 0.755;
sigma_L = M_.params( 11 );
M_.params( 12 ) = 0.5;
lambda_w = M_.params( 12 );
M_.params( 13 ) = 5.91715976331361;
psi = M_.params( 13 );
M_.params( 14 ) = 1.488;
phi = M_.params( 14 );
M_.params( 15 ) = 2.2;
k = M_.params( 15 );
M_.params( 16 ) = 0.18;
g = M_.params( 16 );
M_.params( 17 ) = 0.942;
rho = M_.params( 17 );
M_.params( 18 ) = 1.658;
r_pi = M_.params( 18 );
M_.params( 19 ) = 0.148;
r_Y = M_.params( 19 );
M_.params( 20 ) = 0.199;
r_dpi = M_.params( 20 );
M_.params( 21 ) = 0.173;
r_dY = M_.params( 21 );
M_.params( 22 ) = 0.096;
r_a = M_.params( 22 );
M_.params( 23 ) = 0.047;
r_L = M_.params( 23 );
M_.params( 24 ) = 1/M_.params(3)-1+M_.params(5);
r_k = M_.params( 24 );
M_.params( 26 ) = 0.939;
rho_I = M_.params( 26 );
M_.params( 27 ) = 0.905;
rho_b = M_.params( 27 );
M_.params( 28 ) = 0.962;
rho_L = M_.params( 28 );
M_.params( 29 ) = 0.966;
rho_G = M_.params( 29 );
M_.params( 25 ) = 0.834;
rho_a = M_.params( 25 );
M_.params( 30 ) = 0.924;
rho_pi = M_.params( 30 );
M_.params( 31 ) = 0.603;
sd_Q = M_.params( 31 );
M_.params( 32 ) = 0.16;
sd_p = M_.params( 32 );
M_.params( 33 ) = 0.279;
sd_w = M_.params( 33 );
M_.params( 34 ) = 0.116;
sd_R = M_.params( 34 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
M_.Sigma_e(3, 3) = (1)^2;
M_.Sigma_e(4, 4) = (1)^2;
M_.Sigma_e(5, 5) = (1)^2;
M_.Sigma_e(6, 6) = (1)^2;
M_.Sigma_e(7, 7) = (M_.params(32))^2;
M_.Sigma_e(8, 8) = (M_.params(31))^2;
M_.Sigma_e(9, 9) = (M_.params(34))^2;
M_.Sigma_e(10, 10) = (M_.params(33))^2;
M_.sigma_e_is_diagonal = 1;
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 6 ) = 0;
oo_.steady_state( 5 ) = 0;
oo_.steady_state( 4 ) = 0;
oo_.steady_state( 3 ) = 0;
oo_.steady_state( 1 ) = 0;
oo_.steady_state( 2 ) = 0;
oo_.steady_state( 9 ) = 0;
oo_.steady_state( 10 ) = 0;
oo_.steady_state( 7 ) = 0;
oo_.steady_state( 8 ) = 0;
oo_.steady_state( 11 ) = 0;
oo_.steady_state( 12 ) = 0;
oo_.steady_state( 13 ) = 0;
oo_.steady_state( 14 ) = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 16 ) = 0;
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
options_.irf = 100;
options_.order = 1;
options_.periods = 10000;
var_list_=[];
info = stoch_simul(var_list_);
save('output1.mat','Y', 'C','pi', 'I', 'L', 'w');  
global estim_params_
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 1, NaN, (-Inf), Inf, 1, 0.70, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, (-Inf), Inf, 3, 1.00, 0.375, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, NaN, (-Inf), Inf, 3, 4.00, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 1, 0.75, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 3, 2.00, 0.75, NaN, NaN, NaN ];
options_.first_obs = 1000;
options_.mh_replic = 0;
options_.mode_check = 1;
options_.datafile = 'output1';
options_.nobs = 1000;
options_.order = 1;
var_list_=[];
dynare_estimation(var_list_);
options_.first_obs = 1000;
options_.mh_jscale = 0.9;
options_.mh_nblck = 2;
options_.mh_replic = 10000;
options_.mode_compute = 0;
options_.datafile = 'output1';
options_.mode_file = 'Paper_v3_mode';
options_.nobs = 1000;
options_.order = 1;
var_list_=[];
dynare_estimation(var_list_);
steady;
check(M_,options_,oo_);
save('Paper_v3_results.mat', 'oo_', 'M_', 'options_');


disp(['Total computing time : ' dynsec2hms(toc) ]);
diary off
