function [ys_, params, info] = task1_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=0;
    ys_(2)=0;
    ys_(6)=0;
    ys_(7)=0;
    ys_(5)=0;
    ystar=0;
    y=0;
    ys_(4)=0;
    ys_(3)=0;
    % Auxiliary equations
ys_(8)=exo_(2);
    check_=0;
end
