function [ys_, params, info] = law_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=0;
    ys_(2)=0;
    r=0;
    ys_(5)=1;
    % Auxiliary equations
    check_=0;
end
