function [ys_, params, info] = calib1_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(8)=1;
    ys_(7)=1/params(1)-1+params(3);
    k_over_y=params(4)*(params(7)-1)/params(7)/ys_(7);
    l_over_k=(1/(ys_(8)*k_over_y))^(1/(1-params(4)));
    y_over_l=k_over_y^(-1)*l_over_k^(-1);
    ys_(6)=(params(7)-1)*(1-params(4))*y_over_l/params(7);
    i_over_l=params(3)*l_over_k^(-1);
    c_over_l=y_over_l-params(3)/l_over_k;
    ys_(5)=(1+c_over_l*params(2)/ys_(6))^(-1);
    ys_(2)=c_over_l*ys_(5);
    ys_(1)=y_over_l*ys_(5);
    ys_(3)=ys_(5)/l_over_k;
    ys_(4)=params(3)*ys_(3);
    % Auxiliary equations
    check_=0;
end
