########################## Statistical Inference Winter 2011/12
########################## Class 11
##If you have any questions, please contact me: willi.mutschler@uni-muenster.de

#######################
#### Exercise 16.2 ####
#######################
  #################################################
  #### Confidence intervals for the Gini index ####
  #################################################
  
  #1)
  install.packages("ineq")
  library(ineq)  
  earnings <- read.csv(file.choose(), header=T)
  x <- earnings$x
  ?ineq
  ineq(x,type="Gini")
  Ginihat <- Gini(x)
  print(Ginihat)
  #2)
  n <- length(x)
  B <- 1000
  Ginistar <- rep(NA,B)

  for(b in 1:B) {  
    # Draw a resample
    xx <- sample(x,n,replace=TRUE)  
    # Compute and save the Gini-coefficient for the resample
    Ginistar[b] <- Gini(xx)
    }
    
  # Compute the standard error
  print(sd(Ginistar))
  
  #3)
  # Sort Ginistar
  Ginistar <- sort(Ginistar)
  
  print(paste("Lower limit = ",2*Ginihat-Ginistar[0.975*B]))
  print(paste("Upper limit = ",2*Ginihat-Ginistar[0.025*B]))


#######################
#### Exercise 16.3 ####
#######################
  ###########################################################
  #### Confidence intervals for correlation coefficients ####
  ###########################################################
  #1)
  install.packages("copula")
  library(copula)  
  x <- qexp(rcopula(gumbelCopula(1.3),1000))
  plot(x)
  cor(x)
  
  #2)
  library(AER)
  n <- 50
  x <- qexp(rcopula(gumbelCopula(1.3),n))
  corhat <- cor(x)[1,2]
  B <- 5000
  corstar <- rep(NA,B)

  for(b in 1:B) {
    #Draw a resample
    indices <- sample(1:n,n,replace=T)
    xx <- x[indices,]
    corstar[b] <- cor(xx)[1,2]
  }
  truehist(corstar)
  curve(dnorm(x,mean=mean(corstar),sd=sd(corstar)),add=T)
  # the normal distribution does noch fit
  
  #3)
  corstar <- sort(corstar)
  
  print(paste("Lower limit = ",2*corhat-corstar[0.975*B]))
  print(paste("Upper limit = ",2*corhat-corstar[0.025*B]))
  #poor confidence intervals!


#######################
#### Exercise 16.5 ####
#######################
  #####################
  #### The t-test ####
  ####################
  ttestboot <- read.csv(file.choose())
  x <- ttestboot$x
  y <- ttestboot$y
  n <- length(y)
  #Reminder: the data is generated by a=1, b=0, sigma=2
  
  #1)
  ols <- lm(y~x)
  obj <- summary(ols)
  tols <- obj$coefficients[2,3]
  pols <- obj$coefficients[2,4]
  
  #2)
  alphahat <- coefficients(ols)[1]
  betahat <- coefficients(ols)[2]
  uhat <- residuals(ols)
  sigma2hat <- 1/(n-2)*sum(uhat^2)
  
  #3)
  R <- 5000
  Z <- rep(NA,R)
  
  for(r in 1:R){
    ustar <- rnorm(n,sd=sqrt(sigma2hat))
    ystar <- alphahat + betahat*x + ustar
    olsstar <- lm(ystar~x)
    betahatstar <- coefficients(olsstar)[2]
    SEbetahatstar <- summary(olsstar)$coefficients[2,2]
    Z[r] <- (betahatstar - betahat)/(SEbetahatstar)    
  }
  
  #4)
  library(AER)
  truehist(Z)
  curve(dt(x,df=7),add=T) #the approximation fits perfectly
  
  #5)
  length(Z[abs(Z)>abs(tols)])/length(abs(Z)) 
  pols
  #p-value is almost the same!  
 
 