function [ys_, params, info] = rbc_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(6)=exo_(1)/(1-params(7));
    ys_(5)=params(8)*exp(ys_(6));
    ys_(10)=(1/params(1)-1+params(6))/ys_(5);
    f_over_k=(ys_(10)/params(4))^(1/(1-params(5)));
    c_over_k=ys_(5)*f_over_k-params(6);
    l_over_k=((f_over_k^params(5)-params(4))/(1-params(4)))^(1/params(5));
    f_over_l=f_over_k/l_over_k;
    c_over_l=c_over_k/l_over_k;
    ys_(11)=(1-params(4))*f_over_l^(1-params(5));
    ys_(3)=1/(1+c_over_l*(1-params(2))/params(2)/(f_over_l^(1-params(5))*ys_(5)*(1-params(4))));
    ys_(4)=c_over_l*ys_(3);
    ys_(1)=ys_(3)/l_over_k;
    ys_(12)=(params(4)*ys_(1)^params(5)+(1-params(4))*ys_(3)^params(5))^(1/params(5));
    ys_(2)=ys_(5)*ys_(12);
    ys_(7)=params(6)*ys_(1);
    ys_(8)=(1-ys_(3))^(1-params(2))*params(2)*(ys_(4)^params(2)*(1-ys_(3))^(1-params(2)))^(-params(3))*ys_(4)^(params(2)-1);
    ys_(9)=(-(ys_(4)^params(2)*(1-params(2))*(ys_(4)^params(2)*(1-ys_(3))^(1-params(2)))^(-params(3))*(1-ys_(3))^(-params(2))));
    % Auxiliary equations
    check_=0;
end
