function [ys_, params, info] = AnScho_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=0;
    ys_(2)=0;
    ys_(3)=0;
    ys_(4)=0;
    ys_(5)=0;
    ys_(6)=0;
    ys_(7)=params(13);
    ys_(8)=params(14);
    ys_(9)=params(14)+params(15)+params(13)*4;
    % Auxiliary equations
    check_=0;
end
